Web/Controllers/BookAppointmentController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.Callers;
using Web.CustomAuthorize;
using Web.Models;

namespace Web.Controllers
{
    [LoginRequired]
    public class BookAppointmentController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Uses date to fetch all appointment-times for that date/practitioner using the API/AppointmentCaller.
        /// Also there is a client side validation of the date selected.
        /// </summary>
        /// <param name="date">Find all appointment times on this date</param>
        /// <returns></returns>
        public ActionResult ChooseAppointmentTime(DateTime date)
        {
            DateTime currentDate = new DateTime();
            if (date < currentDate || date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday)
            {
                TempData["ErrorMessage"] = "Du skal vælge en date der er valid og vi holder ikke åben i weekenden!";
                return View();
            }
            AppointmentCaller appointmentCaller = new AppointmentCaller();
            var appointments = appointmentCaller.GetByDate(date, Session["PractitionerId"] as string);
            ViewBag.SelectedDate = date.ToShortDateString();
            return View(appointments);
        }

        /// <summary>
        /// BookTime takes the two datetime objects and uses the API to book a time for the selected date, practitioner and time span selected.
        /// Concurrency issues throws exception with suitable response message. The 'ChoseAppointmentTime'-view is shown with the error message.
        /// </summary>
        /// <param name="startDateTime">aka apointment start time</param>
        /// <param name="endDateTime">aka apointment end time</param>
        /// <returns>The new appoinment is passed to the view if successfull</returns>
        public ActionResult BookTime(DateTime startDateTime, DateTime endDateTime)
        {
            Appointment a = new Appointment();
            a.Enddate = endDateTime;
            a.Startdate = startDateTime;

            a.Customer = Session["UserId"] as string;
            a.Practitioner = Session["PractitionerId"] as string;
            AppointmentCaller ac = new AppointmentCaller();
            try
            {
                ac.BookTime(a);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = e.Message;
                return RedirectToAction("ChooseAppointmentTime", startDateTime.Date);
            }
            return View(a); ;
        }
    }
}

Web/Controllers/LoginController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.Callers;
using Web.Models;

namespace Web.Controllers
{
    public class LoginController : Controller
    {
        /// <summary>
        /// Main Login Page.
        /// </summary>
        /// <returns>Login View</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// User login page. Validates user.
        /// </summary>
        /// <param name="email">The email given by the user</param>
        /// <param name="password">The password given by the user</param>
        /// <returns>Returns to Main/home page if user is valid, else returns login view with error message</returns>
        public async Task<ActionResult> UserLogin(string email, string password)
        {
            LoginCaller lc = new LoginCaller();
            var customer = await lc.GetByLogin(email, password);
            if (customer != null)
            {
                Session["UserId"] = customer.Id.ToString();
                Session["LastName"] = customer.LastName;
                Session["FirstName"] = customer.FirstName;

                PractitionerCaller pc = new PractitionerCaller();
                Practitioner p = await pc.GetPractitionerByURL(customer.Practitioner);
                Session["PractitionerId"] = p.Id.ToString();
                Session["PractitionerFirstName"] = p.FirstName;
                Session["PractitionerLastName"] = p.LastName;
                Session["PractitionerPhoneNo"] = p.PhoneNo;
            }
            else
            {
                TempData["ErrorMessage"] = "Brugeren findes ikke, brugernavn eller password passer ikke";
                return View("Index");
            }
            TempData["SuccessMessage"] = "Du er nu logget ind, velkommen til " + customer.FirstName + "!";
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Logout a user by clearing and deleting the current autheticated session.
        /// </summary>
        /// <returns>Home view with loged out successmessage</returns>
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TrackSpace</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Favicon config -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/content/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/content/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/content/favicon/apple-touch-icon.png">
    <link rel="manifest" href="~/content/favicon/apple-touch-icon.png">
    <link rel="mask-icon" href="~/content/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/">
                    <img src="~/Content/favicon/full_logo.png" class="navbar-brand" />
                    <!--style="height:40px;margin-top:5px;"-->
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(" Home", "Index", "Home")</li>
                    <li>@Html.ActionLink(" Konsultationer", "Index", "BookAppointment")</li>
                    @{
                        if (Session["UserId"] != null)
                        {
                            <li>@Html.ActionLink(" Log ud", "Logout", "Login")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink(" Log på", "Index", "Login")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    @{
        if (TempData["ErrorMessage"] != null)
        {
            <div id="alert" class="alert alert-danger alert-dismissible fade in show">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p> ERROR: @TempData["ErrorMessage"].ToString() </p>
            </div>
        }
    }
    @{
        if (TempData["SuccessMessage"] != null)
        {
            <div id="alert" class="alert alert-success alert-dismissible fade in show">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p> Success: @TempData["SuccessMessage"].ToString() </p>
            </div>
        }
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <a class="pull-left" href="/">TrackSpace.dk </a>
            <p class="pull-right">&copy; @DateTime.Now.Year - TrackSpace Corporation</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>